=== DEMA-UFC/mat-ind/schema/schema-componente-curricular.json
{
	"$schema": "http://json-schema.org/draft-07/schema",
	"title": "Schema para validar um componente curriculare cadastrado nos sistema",
	"definitions": {
		"curso": {
			"tile": "Curso no formulário de criação de disciplina",
			"type": "object",
			"properties": {
				"codigo": {
					"type": "string"
				},
				"nome": {
					"type": "string"
				},
				"grau": {
					"type": "string",
					"enum": [
						"Bacharelado",
						"Licenciatura",
						"Tecnólogo"
					]
				},
				"curriculo": {
					"type": "string"
				},
				"carater": {
					"type": "string",
					"enum": [
						"Obrigatório",
						"Optativo",
						"Eletivo"
					]
				},
				"semestre": {
					"type": "number",
					"minimum": 1,
					"maximum": 8
				},
				"habilitacao": {
					"type": "array",
					"uniqueItems": true,
					"items": {
						"type": "string",
						"enum": [
							"Pesquisa Operacional",
							"Matemática Computacional"
						]
					}
				},
				"unidade-curricular": {
					"title": "Unidade Curricular conforme Projeto Pedagógico do Curso",
					"type": "string",
					"enum": [
						"Métodos Matemáticos",
						"Métodos Estatísticos",
						"Computação",
						"Pesquisa Operacional",
						"Formação Complementar"
					]
				},
				"nucleo-formacao": {
					"title": "Núcleo de Formação conforme Projeto Pedagógico do Curso",
					"type": "string",
					"enum": [
						"Matemática Básica",
						"Computação",
						"Estatística",
						"Matemática Aplicada",
						"Formação Auxiliar",
						"Ênfases",
						"Seminários",
						"Optativa/Livre",
						"Estágio/Monografia",
						"Atividades Complementares"
					]
				}
			},
			"required": [
				"codigo",
				"nome",
				"grau",
				"curriculo",
				"carater"
			]
		},
		"bibliografia": {
			"title": "item de bibliografia de uma disciplina",
			"type": "string"
		}
	},
	"type": "object",
	"properties": {
		"unidade": {
			"type": "string"
		},
		"departamento": {
			"type": "string"
		},
		"curso": {
			"$ref": "#/definitions/curso"
		},
		"nome": {
			"type": "string"
		},
		"codigo": {
			"type": "string"
		},
		"pre-requisitos": {
			"type": "array",
			"uniqueItems": true,
			"items": {
				"type": "string"
			}
		},
		"co-requisitos": {
			"type": "array",
			"uniqueItems": true,
			"items": {
				"type": "string"
			}
		},
		"equivalencias": {
			"type": "array",
			"uniqueItems": true,
			"items": {
				"type": "string"
			}
		},
		"turno": {
			"type": "object",
			"properties": {
				"matutino": {
					"type": "boolean"
				},
				"vespertino": {
					"type": "boolean"
				},
				"noturno": {
					"type": "boolean"
				}
			},
			"required": [
				"matutino",
				"vespertino",
				"noturno"
			]
		},
		"regime": {
			"type": "string",
			"enum": [
				"semestral",
				"anual",
				"modular"
			]
		},
		"justificativa": {
			"type": "string",
			"maxLength": 500
		},
		"objetivos": {
			"type": "array",
			"items": {
				"type": "string"
			}
		},
		"ementa": {
			"$comment": "conforme \"Programa de Disciplina\" aprovado e arquivado pela Unidade Responsável por oferta",
			"type": "array",
			"items": {
				"type": "string"
			}
		},
		"carga-horaria": {
			"type": "object",
			"properties": {
				"semanas": {
					"type": "number",
					"minimum": 0
				},
				"teorica": {
					"type": "number",
					"minimum": 0
				},
				"pratica": {
					"type": "number",
					"minimum": 0
				},
				"ead": {
					"type": "number",
					"minimum": 0
				},
				"extensao": {
					"type": "number",
					"minimum": 0
				}
			}
		},
		"bibliografia": {
			"type": "object",
			"properties": {
				"basica": {
					"type": "array",
					"items": {
						"$ref": "#/definitions/bibliografia"
					},
					"minItems": 3
				},
				"complementar": {
					"type": "array",
					"items": {
						"$ref": "#/definitions/bibliografia"
					},
					"minItems": 5
				}
			}
		},

		"tipo": {
			"title": "Campo somente para atividades.",
			"type": "string",
			"enum": [
				"Estágio Supervisionado",
				"Tutoria/Orientação",
				"Trabalho de Conclusão de Curso/Monografia",
				"Atividades Integradoras de Formação"
			]
		},
		"carga-horaria-docente": {
			"title": "Campo somente para atividades.",
			"type": "number",
			"minimum": 0
		}
	},
	"required": [
		"unidade",
		"curso",
		"nome",
		"codigo",
		"turno",
		"regime",
		"justificativa",
		"objetivos",
		"ementa",
		"carga-horaria",
		"bibliografia"
	]
}

=== DEMA-UFC/mat-ind/_data/componentes-curriculares/ck0109.json
{
    "bibliografia": {
        "basica": [
            "MARKENSON, Lilian; SZWARCFITER, Jayme L. Estruturas de Dados e Seus Algoritmos. LTC Editora, 1994."
        ],
        "complementar": [
            "CORMEN, T. H.; LEISERSON, C. E.; RIVEST, R. L. Introduction to Algorithms. MIT Press e McGraw-Hill, 1990.",
            "AHO, V.; ULLMAN, J. D. Foundation of Computer Science. W. H. Freeman Company, 1992."
        ]
    },
    "carga-horaria": {
        "ead": 0,
        "extensao": 0,
        "pratica": 0,
        "semanas": 16,
        "teorica": 96
    },
    "codigo": "CK0109",
    "curso": {
        "carater": "Obrigatório",
        "codigo": "080",
        "curriculo": "2011.1G",
        "grau": "Bacharelado",
        "nome": "Matemática Industrial",
        "semestre": 2
    },
    "departamento": "Computação",
    "ementa": [
        "Introdução. Listas Lineares. Árvores. Árvores balanceadas. Listas de prioridades. Tabelas de dispersão. Busca digital."
    ],
    "justificativa": "Apresentação de modelos matemáticos que representam tipos abstratos de dados que ocorrem com frequência em algoritmos, além de operações definidas sobre esses modelos.",
    "nome": "Estrutura de Dados",
    "objetivos": [],
    "pre-requisitos": [
        "CK0087"
    ],
    "regime": "semestral",
    "turno": {
        "matutino": true,
        "noturno": false,
        "vespertino": true
    },
    "unidade": "Centro de Ciências"
}

=== DEMA-UFC/mat-ind/_data/componentes-curriculares/cc0281.json
{
    "bibliografia": {
        "basica": [
            "Projeto Político Pedagógico do curso de Matemática Industrial",
            "Projeto Político Pedagógico do curso de Estatística",
            "Manual do Aluno, Pró-reitoria de graduação - http://www.prograd.ufc.br",
            "Site da Universidade Federal do Ceará - http://www.ufc.br"
        ],
        "complementar": []
    },
    "carga-horaria": {
        "ead": 0,
        "extensao": 0,
        "pratica": 0,
        "semanas": 16,
        "teorica": 16
    },
    "codigo": "CC0281",
    "curso": {
        "carater": "Obrigatório",
        "codigo": "080",
        "curriculo": "2011.1G",
        "grau": "Bacharelado",
        "nome": "Matemática Industrial",
        "semestre": 1
    },
    "departamento": "Estatística e Matemática Aplicada",
    "ementa": [
        "Seminários e atividades de orientação acadêmica e de formação básica e profissional, sob orientação de professores tutores."
    ],
    "justificativa": "O aluno do ensino médio ao ingressar na universidade deve ser acolhido e informado sobre os diversos aspectos dessa nova etapa.",
    "nome": "Seminários de Tutoria I",
    "objetivos": [
        "Além acolher o aluno recém-ingresso, o principal objetivo é reduzir a evasão desses durante o primeiro ano na universidade."
    ],
    "regime": "semestral",
    "turno": {
        "matutino": true,
        "noturno": true,
        "vespertino": true
    },
    "unidade": "Centro de Ciências"
}

=== DEMA-UFC/mat-ind/_data/componentes-curriculares/ck0112.json
{
    "bibliografia": {
        "basica": [
            "TORRES, José Júlio Martins. Projeto Estruturado de Programas - apostila.",
            "STAA, Arndt Von. Engenharia de Programas. LTC - Livros Técnicos e Científicos.",
            "WARNIER, Jean Dominique. Lógica de Construção de Programas. Editora Campus. ",
            "JACKSON, Michael. Princípios em Projetos de Programas. Editora Campus.",
            "MARTIN, James; MCCLURE, Carma. Técnicas Estruturadas e Case. Makron Books. ",
            "PAGE-JONES, Meilir. O que Todo Programador Deveria Saber sobre POO. Makron Books. ",
            "SZMIT, R. Programação Orientada para Objetos com Turbo Pascal."
        ],
        "complementar": []
    },
    "carga-horaria": {
        "ead": 0,
        "extensao": 0,
        "pratica": 0,
        "semanas": 16,
        "teorica": 64
    },
    "codigo": "CK0112",
    "curso": {
        "carater": "Obrigatório",
        "codigo": "080",
        "curriculo": "2011.1G",
        "grau": "Bacharelado",
        "nome": "Matemática Industrial",
        "semestre": 3
    },
    "departamento": "Computação",
    "ementa": [
        "Técnicas de programação. Projeto estruturado de programas. Projeto lógico de programas. Implementação do projeto. Construção de programas. Testes de programas. Evolução de programas. Ambientes de programação. Ferramentas Case. Programação orientada a objetos. Linguagens de programação orientadas a objetos."
    ],
    "equivalencias": [
        "CK0235"
    ],
    "justificativa": "Iniciar os alunos nas técnicas estruturadas de projeto e implementação de programas, abordando definições de conceitos e a evolução das técnicas estruturadas de programação. São apresentadas também as técnicas de projetos, implementação, construção, teste e evolução de programas bem como as técnicas de programação orientadas a objetos.",
    "nome": "Técnicas de Programação I",
    "objetivos": [],
    "pre-requisitos": [
        "CK0087"
    ],
    "regime": "semestral",
    "turno": {
        "matutino": true,
        "noturno": false,
        "vespertino": false
    },
    "unidade": "Centro de Ciências"
}

=== DEMA-UFC/mat-ind/_data/componentes-curriculares/cc0400.json
{
    "bibliografia": {
        "basica": [
            "CORNACHIONE JR, Edgard B. Informática aplicada ás áreas de contabilidade, administração e economia. 3.ed. São Paulo: Atlas, 2001.",
            "DATE, C. Introdução a sistemas de bancos de dados. Rio de Janeiro: Campus, 2000.",
            "HEUSER, C. A. Projeto de bancos de dados. Porto Alegre: Sagra-Luzzatto, 2000.",
            "NORTON, Peter. Introdução à informática. São Paulo: Makron Books, 1996.",
            "SANTOS, Aldemar de Araújo. Informática na empresa. 2.ed. São Paulo: Atlas, 2000.",
            "TORRES. Norberto Antonio. Planejamento de informática na empresa. São Paulo: Atlas, 1991."
        ],
        "complementar": []
    },
    "carga-horaria": {
        "ead": 0,
        "extensao": 0,
        "pratica": 32,
        "semanas": 16,
        "teorica": 32
    },
    "codigo": "CC0400",
    "curso": {
        "carater": "Eletivo",
        "codigo": "080",
        "curriculo": "2011.1G",
        "grau": "Bacharelado",
        "habilitacao": [
            "Matemática Computacional",
            "Pesquisa Operacional"
        ],
        "nome": "Matemática Industrial",
        "semestre": 4
    },
    "departamento": "Estatística e Matemática Aplicada",
    "ementa": [
        "Conceitos básicos de informática. Introdução aos Sistemas de Informação. A evolução da TI. Componentes da Tecnologia de Informação: Hardware, Software. Redes e Telecomunicações. Evolução dos SGBDs. Arquitetura geral dos SGBDs. Modelagem de dados. Modelo Entidade e Relacionamento (MER). Linguagens de definição e manipulação de dados. Operações com relações e mapeamento para SQL. Elaboração de um  Projeto de Bancos de Dados para uma aplicação real, contendo especificações de todas as fases de Análise e Modelagem envolvidas: Modelo Conceitual, Análise (OO ou Essencial), Projetos Lógico e Físico."
    ],
    "justificativa": "Familiarizar o aluno com as t Familiarizar o aluno com as tecnologias e metodologias para desenvolvimento de aplicações de maior grau de complexidade. Capacitar o aluno a implementar soluções utilizando bancos de dados apresentando as diversas tecnologias da área.",
    "nome": "Tecnologia da Informação",
    "objetivos": [
        "O que se pretende não é formar cientistas de computação ou analistas de sistemas, mas sim oferecer ao aluno uma visão ampla das potencialidades dos recurso da Tecnologia da Informação como instrumento de apoio ao trabalho do dia-a-dia. A maior parte do curso será dedicada ao uso de equipamentos para assimilação das principais ferramentas de trabalho que o aluno utilizará amplamente durante todo o curso e, sobretudo, durante sua vida profissional. Para isto, os alunos desenvolverão projetos de aplicação prática dos recurso apresentados, visando melhor sedimentação dos conhecimentos adquiridos."
    ],
    "regime": "semestral",
    "turno": {
        "matutino": true,
        "noturno": false,
        "vespertino": true
    },
    "unidade": "Centro de Ciências"
}

=== DEMA-UFC/mat-ind/_data/componentes-curriculares/cc0327.json
{
    "bibliografia": {
        "basica": [
            "S.M. Ross. Simulation. Academic Press, 2006.",
            "P.J. Freitas. Introdução à modelagem e simulação de sistemas com aplicações arena. Visual Books, 2008.",
            "L. Chwif e A.C Medina. Modelagem e simulação de eventos discretos. Leonardo Chwif, 2010.",
            "D.S. Prado. Teoria das filas e da simulação. INGD, 2004.",
            "A. O. Allen. Probability, Statistics, and Queuing Theory With Computer Science Applications, Academic Press; 2nd ed., 1990."
        ],
        "complementar": []
    },
    "carga-horaria": {
        "ead": 0,
        "extensao": 0,
        "pratica": 32,
        "semanas": 16,
        "teorica": 32
    },
    "codigo": "CC0327",
    "curso": {
        "carater": "Obrigatório",
        "codigo": "080",
        "curriculo": "2011.1G",
        "grau": "Bacharelado",
        "nome": "Matemática Industrial",
        "semestre": 6
    },
    "departamento": "Estatística e Matemática Aplicada",
    "ementa": [
        "Teoria das Filas: Fundamentos e conceitos básicos sobre teoria das filas, comportamento estático e dinâmico dos sistemas de filas, medição de performance em sistema de filas, modelos M/M/1. Técnicas de Simulação: terminologia em simulação, exemplos de modelos simulação. Verificação e validação de modelos de simulação. Modelos de simulações diversos. Softwares de simulação."
    ],
    "justificativa": "Os alunos de Matemática industrial necessitam dos conteúdos apresentados na disciplina de simulação estocástica, pois amostras de variáveis aleatórias devem ser geradas em um ambiente computacional a fim de obter um determinado resultado para problemas reais. A disciplina é direcionada a estudantes de graduação em Matemática Industrial ou área afins que possuam noções de probabilidades e estatística.",
    "nome": "Simulação Estocástica",
    "objetivos": [
        "O objetivo principal é fornecer ao aluno uma introdução aos vários aspectos da simulação estocástica."
    ],
    "pre-requisitos": [
        "CC0288"
    ],
    "regime": "semestral",
    "turno": {
        "matutino": true,
        "noturno": false,
        "vespertino": true
    },
    "unidade": "Centro de Ciências"
}

=== DEMA-UFC/mat-ind/_data/componentes-curriculares/ck0048.json
{
    "bibliografia": {
        "basica": [
            "Nakamura, S., “Applied Numerical Methods in C,” Prentice Hall, Englewood Cliffs, NJ, 1993. ",
            "Cládio, D.M. et al, “Cálculo Numérico Computacional - Teoria e Prática,” Ed. Atlas, 1990. ",
            "Ruggiero, M.A.G. e Lopes, V.L.R., “Cálculo Numérico - Aspectos Teóricos e Computacionais,” McGraw-Hill do Brasil, 1988. ",
            "Press, W.H., Flannery, B.P., Teukolsky, S.A. and Vetterling, W.T., “Numerical Recipes - The Art of Scientific Computing,” Cambridge University Press, Cambridge, MA, 1986. ",
            "Golub, G.H and Loan, C.F., “Matrix Computations,” The Johns Hopkins University Press, Baltimore, Maryland, 1989. ",
            "Jennings, A., “Matrix Computation for Engineers and Scientists,” John Wiley & Sons, NY, 1980."
        ],
        "complementar": []
    },
    "carga-horaria": {
        "ead": 0,
        "extensao": 0,
        "pratica": 0,
        "semanas": 16,
        "teorica": 64
    },
    "codigo": "CK0048",
    "curso": {
        "carater": "Obrigatório",
        "codigo": "080",
        "curriculo": "2011.1G",
        "grau": "Bacharelado",
        "nome": "Matemática Industrial",
        "semestre": 5
    },
    "departamento": "Computação",
    "ementa": [
        "Integração Numérica; Diferenciação Numérica; Cálculo de Autovalores e Autovetores de Matrizes; Solução de Problemas de Valores Iniciais de Equações Diferenciais Ordinárias; Solução de Problemas de Valores de Contorno de Equações Diferenciais."
    ],
    "justificativa": "Tornar o aluno apto a identificar os métodos numéricos mais adequados a: integração numérica, diferenciação numérica; cálculo de autovalores de matrizes; solução de problemas de valores iniciais de EDO’s; solução de problemas de valores de contorno. O aluno será apto, também, a conhecer os fundamentos dos métodos numéricos de forma a propor modificações para criação de novos métodos ou identificar a causa dos erros.",
    "nome": "Métodos Numéricos II",
    "objetivos": [],
    "pre-requisitos": [
        "CK0047"
    ],
    "regime": "semestral",
    "turno": {
        "matutino": true,
        "noturno": false,
        "vespertino": true
    },
    "unidade": "Centro de Ciências"
}

=== DEMA-UFC/mat-ind/_data/componentes-curriculares/cc0325.json
{
    "bibliografia": {
        "basica": [
            "D. Watkins. Fundamentals of Matrix Computations. J. Wiley, 2006.",
            "G. Golub e C. Van Loan. Matrix Computations. Johhs Hopkins University Press, 3a. edição, 1996. ",
            "J. Demmel. Applied Numerical Linear Algebra. SIAM, 1997. ",
            "L. Trefethen e D. Bau. Numerical Linear Algebra. SIAM, 2000. ",
            "P. Gill, W. Murray e M. Wright. Numerical Linear Algebra and Optimization, Addison-Wesley Company, 1991. ",
            "J.M. Ortega. Matrix Theory - a second course. Plenum Press, 1987. ",
            "S.R. Searle. Matrix Algebra Useful for Statistics. John Wiley & Sons, New York, 1982. ",
            "B. Noble e J.W. Daniel. Álgebra Linear Aplicada. Prentice Hall do Brasil, 1986. "
        ],
        "complementar": []
    },
    "carga-horaria": {
        "ead": 0,
        "extensao": 0,
        "pratica": 16,
        "semanas": 16,
        "teorica": 48
    },
    "codigo": "CC0325",
    "curso": {
        "carater": "Eletivo",
        "codigo": "080",
        "curriculo": "2011.1G",
        "grau": "Bacharelado",
        "habilitacao": [
            "Pesquisa Operacional",
            "Matemática Computacional"
        ],
        "nome": "Matemática Industrial",
        "semestre": 6
    },
    "departamento": "Estatística e Matemática Aplicada",
    "ementa": [
        "Revisão de Álgebra Linear. Algoritmos para multiplicação matricial e sistemas triangulares. Métodos diretos para sistemas lineares. Decomposição LU, método de Gauss. Inversão de matrizes. Matrizes definidas positivas. Decomposição de Cholesky. Decomposição QR. Mínimos quadrados. Esparsidade. Condicionamento. Análise de erros. Métodos iterativos para sistemas lineares. Convergência. Determinação numérica de autovalores e autovetores. Implementações computacionais."
    ],
    "justificativa": "Muitos problemas de engenharia e matemática industrial demandam a resolução de sistemas de equações lineares. Conhecer os métodos básicos para solução de sistemas lineares gerais e saber adaptá-los conforme a necessidade, explorando as propriedades de um sistema particular ou as características da máquina  linguagem onde serão implementados, é ponto fundamental na formação de um profissional da área. Essa disciplina apresenta e avalia os principais métodos em álgebra linear computacional.",
    "nome": "Álgebra Linear Computacional",
    "objetivos": [
        "Prover o aluno com conhecimento e experiência computacional na solução de problemas de Álgebra Linear, especialmente a resolução de sistemas lineares."
    ],
    "pre-requisitos": [
        "CB0589",
        "CK0047"
    ],
    "regime": "semestral",
    "turno": {
        "matutino": true,
        "noturno": false,
        "vespertino": true
    },
    "unidade": "Centro de Ciências"
}

=== DEMA-UFC/mat-ind/_data/componentes-curriculares/cc0297.json
{
    "bibliografia": {
        "basica": [
            "Durret, R. (1999). Essentials of Stochastic Processes. New York: Springer-Verlag.",
            "Grimmet, G.R. and Stirzaker, D.R. (1992). Probability and Random Processes, 2 nd ed. Hong Kong: Oxford Universty Press.",
            "Norris, J.M. (1999). Markov Chains. Cambridge: Cambridge University Press.",
            "Ross, S.M. (1995). Stochastic Processes.New York: Wiley.",
            "Ross, S. M. (2006). Simulation, 4 th ed. California: Academic Press. ",
            "Ross, S.M. 2007). Introduction to Probability Models, 9 th ed. California: Academic Press.",
            "Hoel, P.G, Port, S.C. and Stone, C.J. (1986). Introduction to Stochastic Processes. Illinois: Wavelend Press.",
            "Guttorp, P. (1995).  Stochastic Modeling of Scientific Data.  London: Chapman & Hall.",
            "Muller D. (2007). Processos Estocásticos e Aplicações. 1ª ed. Almedina. 9789724029344",
            "de Almeida J.P., Mauro J. e Alves W. (2008). Probabilidade, Variáveis e Processos Estocásticos. 1ª ed. Interciencia. 8571931917",
            "Cappé, O., Moulines, E. and Ryden, T. (2005). Inference in Hidden Markov Models. New York:Springer.",
            "Feller, W. (1970). An introduction to probability theory and its applications, vol 1, 3rd edition. New Yok: John Wiley.",
            "Feller, W. (1976). Introdução à Teoria das probabilidades, parte 1- Espaços amostrais discretos. São Paulo: Edgar Blucher.",
            "Ferrari, P.A. and Galves, J.A. (1997). Acoplamento em Processos Estocásticos. XXI Colóquio Brasileiro de Matemática: Rio de Janeiro.",
            "Mamon, R.S. and Elliot, R.J. (2007). Hidden Markov Models in Finance. York:Springer.",
            "Klebaner, F. C. (2006). Introduction to Stochastic Calculus with Applications, 2 nd ed. London: Imperial College Press."
        ],
        "complementar": []
    },
    "carga-horaria": {
        "ead": 0,
        "extensao": 0,
        "pratica": 16,
        "semanas": 16,
        "teorica": 80
    },
    "codigo": "CC0297",
    "curso": {
        "carater": "Eletivo",
        "codigo": "080",
        "curriculo": "2011.1G",
        "grau": "Bacharelado",
        "habilitacao": [
            "Matemática Computacional"
        ],
        "nome": "Matemática Industrial",
        "semestre": 4
    },
    "departamento": "Estatística e Matemática Aplicada",
    "ementa": [
        "Cadeias de Markov em tempo discreto, cadeias de Markov em tempo contínuo, classificação de estados, distribuição estacionária, teorema ergódico, inferência em cadeias de Markov, aplicações de processos estocásticos."
    ],
    "justificativa": "Apresentar a teoria básica de processos estocásticos, propiciando assim, ao aluno a utilização da teoria de processos estocásticos em situações da sua área de interesse.",
    "nome": "Introdução aos Processos Estocásticos",
    "objetivos": [
        "Apresentar ao aluno os conceitos dos processos estocásticos e suas aplicações."
    ],
    "pre-requisitos": [
        "CC0319"
    ],
    "regime": "semestral",
    "turno": {
        "matutino": true,
        "noturno": false,
        "vespertino": true
    },
    "unidade": "Centro de Ciências"
}
