=== DEMA-UFC/mat-ind/schema/schema-componente-curricular.json
{
	"$schema": "http://json-schema.org/draft-07/schema",
	"title": "Schema para validar um componente curriculare cadastrado nos sistema",
	"definitions": {
		"curso": {
			"tile": "Curso no formulário de criação de disciplina",
			"type": "object",
			"properties": {
				"codigo": {
					"type": "string"
				},
				"nome": {
					"type": "string"
				},
				"grau": {
					"type": "string",
					"enum": [
						"Bacharelado",
						"Licenciatura",
						"Tecnólogo"
					]
				},
				"curriculo": {
					"type": "string"
				},
				"carater": {
					"type": "string",
					"enum": [
						"Obrigatório",
						"Optativo",
						"Eletivo"
					]
				},
				"semestre": {
					"type": "number",
					"minimum": 1,
					"maximum": 8
				},
				"habilitacao": {
					"type": "array",
					"uniqueItems": true,
					"items": {
						"type": "string",
						"enum": [
							"Pesquisa Operacional",
							"Matemática Computacional"
						]
					}
				},
				"unidade-curricular": {
					"title": "Unidade Curricular conforme Projeto Pedagógico do Curso",
					"type": "string",
					"enum": [
						"Métodos Matemáticos",
						"Métodos Estatísticos",
						"Computação",
						"Pesquisa Operacional",
						"Formação Complementar"
					]
				},
				"nucleo-formacao": {
					"title": "Núcleo de Formação conforme Projeto Pedagógico do Curso",
					"type": "string",
					"enum": [
						"Matemática Básica",
						"Computação",
						"Estatística",
						"Matemática Aplicada",
						"Formação Auxiliar",
						"Ênfases",
						"Seminários",
						"Optativa/Livre",
						"Estágio/Monografia",
						"Atividades Complementares"
					]
				}
			},
			"required": [
				"codigo",
				"nome",
				"grau",
				"curriculo",
				"carater"
			]
		},
		"bibliografia": {
			"title": "item de bibliografia de uma disciplina",
			"type": "string"
		}
	},
	"type": "object",
	"properties": {
		"unidade": {
			"type": "string"
		},
		"departamento": {
			"type": "string"
		},
		"curso": {
			"$ref": "#/definitions/curso"
		},
		"nome": {
			"type": "string"
		},
		"codigo": {
			"type": "string"
		},
		"pre-requisitos": {
			"type": "array",
			"uniqueItems": true,
			"items": {
				"type": "string"
			}
		},
		"co-requisitos": {
			"type": "array",
			"uniqueItems": true,
			"items": {
				"type": "string"
			}
		},
		"equivalencias": {
			"type": "array",
			"uniqueItems": true,
			"items": {
				"type": "string"
			}
		},
		"turno": {
			"type": "object",
			"properties": {
				"matutino": {
					"type": "boolean"
				},
				"vespertino": {
					"type": "boolean"
				},
				"noturno": {
					"type": "boolean"
				}
			},
			"required": [
				"matutino",
				"vespertino",
				"noturno"
			]
		},
		"regime": {
			"type": "string",
			"enum": [
				"semestral",
				"anual",
				"modular"
			]
		},
		"justificativa": {
			"type": "string",
			"maxLength": 500
		},
		"objetivos": {
			"type": "array",
			"items": {
				"type": "string"
			}
		},
		"ementa": {
			"$comment": "conforme \"Programa de Disciplina\" aprovado e arquivado pela Unidade Responsável por oferta",
			"type": "array",
			"items": {
				"type": "string"
			}
		},
		"carga-horaria": {
			"type": "object",
			"properties": {
				"semanas": {
					"type": "number",
					"minimum": 0
				},
				"teorica": {
					"type": "number",
					"minimum": 0
				},
				"pratica": {
					"type": "number",
					"minimum": 0
				},
				"ead": {
					"type": "number",
					"minimum": 0
				},
				"extensao": {
					"type": "number",
					"minimum": 0
				}
			}
		},
		"bibliografia": {
			"type": "object",
			"properties": {
				"basica": {
					"type": "array",
					"items": {
						"$ref": "#/definitions/bibliografia"
					},
					"minItems": 3
				},
				"complementar": {
					"type": "array",
					"items": {
						"$ref": "#/definitions/bibliografia"
					},
					"minItems": 5
				}
			}
		},

		"tipo": {
			"title": "Campo somente para atividades.",
			"type": "string",
			"enum": [
				"Estágio Supervisionado",
				"Tutoria/Orientação",
				"Trabalho de Conclusão de Curso/Monografia",
				"Atividades Integradoras de Formação"
			]
		},
		"carga-horaria-docente": {
			"title": "Campo somente para atividades.",
			"type": "number",
			"minimum": 0
		}
	},
	"required": [
		"unidade",
		"curso",
		"nome",
		"codigo",
		"turno",
		"regime",
		"justificativa",
		"objetivos",
		"ementa",
		"carga-horaria",
		"bibliografia"
	]
}

=== DEMA-UFC/mat-ind/_data/componentes-curriculares/cc0328.json
{
    "bibliografia": {
        "basica": [
            "Guia de Normalização de Trabalhos Acadêmicos da Universidade Federal do Ceará, 2012., http://www.biblioteca.ufc.br/ acessado em 05/2012.",
            "Periódicos diversos. http://www.periodicos.capes.gov.br/ acessado em 05/2012."
        ],
        "complementar": []
    },
    "carga-horaria": {
        "ead": 0,
        "extensao": 0,
        "pratica": 32,
        "semanas": 16,
        "teorica": 32
    },
    "codigo": "CC0328",
    "curso": {
        "carater": "Eletivo",
        "codigo": "080",
        "curriculo": "2011.1G",
        "grau": "Bacharelado",
        "habilitacao": [
            "Pesquisa Operacional"
        ],
        "nome": "Matemática Industrial",
        "semestre": 7
    },
    "departamento": "Estatística e Matemática Aplicada",
    "ementa": [
        "Disciplina com ementa aberta, com tópicos variáveis, não contemplados integralmente nas demais disciplinas, oferecida por solicitação do professor do corpo docente, com aprovação do colegiado. O professor deverá definir um subtítulo e apresentar uma ementa na área de concentração de Pesquisa Operacional."
    ],
    "justificativa": "Disciplina com conteúdos variados, não contemplados integralmente nas demais disciplinas.",
    "nome": "Laboratório de Otimização",
    "objetivos": [
        "Apresentar e discutir tópicos variados com aplicações em Pesquisa Operacional."
    ],
    "pre-requisitos": [
        "CK0019",
        "CC0399"
    ],
    "regime": "semestral",
    "turno": {
        "matutino": true,
        "noturno": false,
        "vespertino": true
    },
    "unidade": "Centro de Ciências"
}

=== DEMA-UFC/mat-ind/_data/componentes-curriculares/cc0322.json
{
    "bibliografia": {
        "basica": [
            "AHUJA R.K., MAGNANTI T.L., ORLIN J.B., Network Flows - theory, algorithms and applications. Prentice Hall 1993.",
            "ARENALES, M., ARMENTANO, V., MORABITO, R., YANASSE, H. Pesquisa Operacional, Ed. Campus, 3a edição, 2007.",
            "GOLBARG, M. C., LUNNA. H. P. L. Otimização Combinatória e Programação Linear - Modelos e Algoritmos, Ed. Campus, 2a edição, 2005."
        ],
        "complementar": [
            "FAURE, R., LEMAIRE,B., PICOULEAU, C. Précis de recherche opérationnelle – méthodes et exercices d´applications, Ed. DUNOD, 5a édition, 2000."
        ]
    },
    "carga-horaria": {
        "ead": 0,
        "extensao": 0,
        "pratica": 16,
        "semanas": 16,
        "teorica": 48
    },
    "codigo": "CC0322",
    "curso": {
        "carater": "Eletivo",
        "codigo": "080",
        "curriculo": "2011.1G",
        "grau": "Bacharelado",
        "habilitacao": [
            "Pesquisa Operacional"
        ],
        "nome": "Matemática Industrial",
        "semestre": 5
    },
    "departamento": "Estatística e Matemática Aplicada",
    "ementa": [
        "Conceitos e definições de grafos. Representação de grafos. Grafos Eulerianos e Hamiltonianos. Percurso em grafos. Conexidade. Árvore geradora mínima e variações. Caminhos mínimos. Fluxo máximo e variações. Emparelhamentos. Localização de facilidades. Coloração. Problemas de transporte. Aplicações em grafos."
    ],
    "justificativa": "Grande parte dos problemas de otimização combinatória de alta complexidade computacional ocorre em uma estrutura denominada de rede ou grafo (um conjunto de pontos relacionados por um conjunto de conexões entre eles). Exemplos práticos são as redes de transporte de corrente elétrica, de telecomunicações, de transporte terrestre e ferroviário, de abastecimento de água, de coleta e transporte de petróleo bruto de poços à refinarias, etc. Quantos aos diversos tipos de problemas com essa estrutura, citamos o roteamento de custo mínimo entre dois pontos de uma rede terrestre, o transporte de dados em redes de telecomunicações e expansão de capacidade de transporte de tais redes, localização de estações de base de transmissão celular e alocação de freqüências de comunicação entre elas, etc. Modelos matemáticos para esses problemas são obtidos a partir da estrutura em grafo que o representa e as técnicas de resolução são baseadas em algoritmos clássicos em grafos envolvendo, por exemplo, percurso, árvore geradora, emparelhamento, coloração de vértices ou arestas, etc.",
    "nome": "Otimização em Redes",
    "objetivos": [
        "Possibilitar ao aluno aprofundar seus conhecimentos em problemas práticos de otimização combinatória com estrutura de rede, desenvolvendo algoritmos específicos para esses problemas."
    ],
    "regime": "semestral",
    "turno": {
        "matutino": true,
        "noturno": false,
        "vespertino": true
    },
    "unidade": "Centro de Ciências"
}

=== DEMA-UFC/mat-ind/_data/componentes-curriculares/cc0323.json
{
    "bibliografia": {
        "basica": [
            "E.K.P. Chong, S.H. Zak. An introduction to optimization 3ª Ed. Wiley-Iterscience, 2008.",
            "D. G. Luenberger, Y. Ye, Linear and nonlinear programming 3ª Ed. Springer, 2008.",
            "R. Fletcher. Practical methods of optimization.  Wiley, 2000.",
            "A. Friedlander. Elementos de programação não-linear. Unicamp, 1994.",
            "A. Izmailov, M. Solodov1. Otimização Vol. 1, Condições de otimalidade, elementos de análise convexa e de dualidade. IMPA, 2005.",
            "A. Izmailov, M. Solodov. Otimização Vol. 2, Métodos Computacionais, elementos de análise convexa e de dualidade. IMPA, 2007."
        ],
        "complementar": []
    },
    "carga-horaria": {
        "ead": 0,
        "extensao": 0,
        "pratica": 16,
        "semanas": 16,
        "teorica": 48
    },
    "codigo": "CC0323",
    "curso": {
        "carater": "Eletivo",
        "codigo": "080",
        "curriculo": "2011.1G",
        "grau": "Bacharelado",
        "habilitacao": [
            "Pesquisa Operacional",
            "Matemática Computacional"
        ],
        "nome": "Matemática Industrial",
        "semestre": 5
    },
    "departamento": "Estatística e Matemática Aplicada",
    "ementa": [
        "Definição e classificação de problemas de otimização; Definição de algoritmos iterativos e convergência; Condições de otimalidade em problemas irrestritos; Convexidade e suas relações com a otimização; Convergência global de algoritmos de descida; Velocidade de convergência; Busca unidimensional; Métodos básicos de minimização multidimensional irrestrita: gradiente, Newton e Broyden; Condições de otimalidade em problemas restritos (KKT); Dualidade global e local; Métodos básicos de minimização multidimensional em problemas restritos: métodos de penalidade, métodos de barreira, programação quadrática sequencial e gradiente reduzido generalizado."
    ],
    "justificativa": "O campo da otimização possui dois ramos centrais: a programação linear e a programação não-linear. Esta última com diversas aplicações nas mais diversas áreas desde estatística, passando por física e, consequentemente, engenharias. Os métodos e tecnologias da programação não-linear partem do cálculo e álgebra linear, mas seguem estruturação específica, carecendo portanto de tratamento individualizado.",
    "nome": "Programação Não-Linear",
    "objetivos": [
        "Apresentar os conceitos fundamentais da programação não-linear: a caracterização dos problemas não-lineares uni e multidimensionais, condições de otimalidade, definição formal de algoritmo,  métodos clássicos de otimização e sua convergência."
    ],
    "pre-requisitos": [
        "CB0535",
        "CB0589"
    ],
    "regime": "semestral",
    "turno": {
        "matutino": true,
        "noturno": false,
        "vespertino": true
    },
    "unidade": "Centro de Ciências"
}

=== DEMA-UFC/mat-ind/_data/componentes-curriculares/cc0332.json
{
    "bibliografia": {
        "basica": [
            "G. Golub e C. Van Loan. Matrix Computations. Johhs Hopkins University Press, 3a. Edição, 1996",
            "D. Watkins. Fundamentals of Matrix Computations. J. Wiley, 2006. ",
            " J. Demmel. Applied Numerical Linear Algebra. SIAM, 1997. ",
            "L. Trefethen e D. Bau. Numerical Linear Algebra. SIAM, 2000. ",
            "P. Gill, W. Murray e M. Wright. Numerical Linear Algebra and Optimization, Addison-Wesley Company, 1991.",
            "R. Horn e C. Johnson. Matrix Analysis. Cambridge University Press, 1999. "
        ],
        "complementar": []
    },
    "carga-horaria": {
        "ead": 0,
        "extensao": 0,
        "pratica": 16,
        "semanas": 16,
        "teorica": 48
    },
    "codigo": "CC0332",
    "curso": {
        "carater": "Optativo",
        "codigo": "080",
        "curriculo": "2011.1G",
        "grau": "Bacharelado",
        "nome": "Matemática Industrial"
    },
    "departamento": "Estatística e Matemática Aplicada",
    "ementa": [
        "Métodos diretos para sistemas lineares de grande porte. Análise de precisão e refinamento da solução.  Estimativa do condicionamento. Decomposições LU e  Cholesky em bloco. Sistemas tridiagonais e Hessenberg. Ortogonalização e Mínimos quadrados. Decomposição QR em bloco. Determinação numérica do posto da matriz. Decomposição em valores singulares. Determinação de autovalores e autovetores de matrizes simétricas e não simétricas. Métodos de potências e QR. Métodos iterativos para sistemas lineares: Métodos split, Gradientes conjugados e Métodos de Krylov. Pré-condicionadores. Convergência. Implementações computacionais, sequenciais e paralelas."
    ],
    "justificativa": "Esse curso revisita os principais métodos e Álgebra Linear Computacional, focando em aspectos como esparsidade, simetria, decomponibilidade em blocos, eficiência computacional, implementações que possam tirar proveito da arquitetura e linguagem utilizadas, de modo a aumentar o desempenho computacional em sistemas de grande porte. Questões relativas à qualidade da solução obtida, como condicionamento do problema, refinamento e precisão da solução também são explorados. Decomposições e métodos mais avançados, que complementam ou generalizam aqueles vistos na primeira disciplina de Álgebra Linear Computacional, integram ainda o escopo desse segundo curso.",
    "nome": "Álgebra Linear Computacional de Grande Porte",
    "objetivos": [
        "Prover o aluno com conhecimento e experiência computacional na solução de problemas de Álgebra Linear, especialmente a resolução de sistemas lineares de grande porte e a determinação de autovalores e autovetores."
    ],
    "pre-requisitos": [
        "CC0325"
    ],
    "regime": "semestral",
    "turno": {
        "matutino": true,
        "noturno": false,
        "vespertino": true
    },
    "unidade": "Centro de Ciências"
}

=== DEMA-UFC/mat-ind/_data/componentes-curriculares/cc0288.json
{
    "bibliografia": {
        "basica": [
            "Bussab, W.O. e Morettin, P.A. (2010). Estatística Básica, 6a edição. Saraiva: São Paulo.",
            "Casella, G. e Berger, L.R. (2001). Statistical Inference, 2nd edition. Duxbury Press: New York.",
            "Casella, G. e Berger, L.R. (2011). Inferência Estatística, tradução da 2a edicao norte-americana. São Paulo: CENGACE Learning.",
            "Devore, J.L. (2006). Probabilidade e Estatística para Engenharia e Ciências. Thomson: São Paulo.",
            "Mood, A. M., Graybill, F  e  Boes, D. C . (1974). Introduction to the Theory of Statistics, 3rd edition. McGraw-Hill: New York.",
            "Bolfarine, H. e Sandoval, M. C. (2001).  Introdução à Inferência Estatística. Coleção Matemática Aplicada. Editora SBM: Rio de Janeiro.",
            "Bickel, P.J. e Doksum, K.A. (2007). Mathematical Statistics, vol I 2nd edition. Prentice Hall: New Jersey.",
            "Dudewicz, E.J. e Mishra, S.N. (1988). Modern Mathematical Statistics. John Wiley: New York."
        ],
        "complementar": []
    },
    "carga-horaria": {
        "ead": 0,
        "extensao": 0,
        "pratica": 0,
        "semanas": 16,
        "teorica": 96
    },
    "codigo": "CC0288",
    "curso": {
        "carater": "Obrigatório",
        "codigo": "080",
        "curriculo": "2011.1G",
        "grau": "Bacharelado",
        "nome": "Matemática Industrial",
        "semestre": 5
    },
    "departamento": "Estatística e Matemática Aplicada",
    "ementa": [
        "Conceitos de população e amostra; parâmetros, estatísticas, estimadores e suas propriedades; Distribuições amostrais; Métodos de estimação pontual: momentos, máxima verossimilhança, mínimos quadrados; Estimação intervalar; testes de hipóteses; Testes de homogeneidade e independência."
    ],
    "justificativa": "Familiarizar o aluno com os conceitos básicos e inferência Estatística, permitindo que o mesmo possa entender o processo inferencial, no que diz respeito à amostragem, estimação e testes de hipótese. O aluno deve estar apto a fazer com testes de envolvendo os parâmetros mais usuais (média, variância e proporção).",
    "nome": "Inferência Estatística I",
    "objetivos": [
        "Conhecer conceitos próprios da Inferência Estatística; estabelecer distribuições amostrais de estimadores e suas propriedades; identificar e fazer uso dos métodos de estimação; obter estimadores pontuais e intervalares; realizar testes de hipóteses."
    ],
    "pre-requisitos": [
        "CB0536",
        "CC0319"
    ],
    "regime": "semestral",
    "turno": {
        "matutino": true,
        "noturno": false,
        "vespertino": true
    },
    "unidade": "Centro de Ciências"
}

=== DEMA-UFC/mat-ind/_data/componentes-curriculares/ck0047.json
{
    "bibliografia": {
        "basica": [
            "Ruggiero, M.A.G. e Lopes, V.L.R., Cálculo Numérico. Makron Books, 1996.",
            "Cláudio, D.M. e Marins, J.M., Cálculo Numérico Computacional. Atlas, 1988.",
            "Barroso, L. at al., Cálculo Numérico. Harbra, 1987.",
            "Ruas, V., Curso de Cálculo Numérico. LTC, 1983.",
            "Conte, S.D., Elementos de Análise Numérica. Globo, 1971.",
            "Dorn, W.S. e McCracken, D.D., Cálculo Numérico com Estudos de Casos em Fortran. Campus, 1978.",
            "Forsythe, R. at al., Numerical Methods for Mathematical Computations. Prentice-Hall Inc., 1979.",
            "Press, W.H. at al., Numerical Recipes- The Art of Scientific Computing. Cambridge Univ. Press, 1986."
        ],
        "complementar": []
    },
    "carga-horaria": {
        "ead": 0,
        "extensao": 0,
        "pratica": 0,
        "semanas": 16,
        "teorica": 64
    },
    "codigo": "CK0047",
    "curso": {
        "carater": "Eletivo",
        "codigo": "080",
        "curriculo": "2011.1G",
        "grau": "Bacharelado",
        "habilitacao": [
            "Matemática Computacional"
        ],
        "nome": "Matemática Industrial",
        "semestre": 4
    },
    "departamento": "Computação",
    "ementa": [
        "Introdução a Métodos Numéricos; Teoria dos Erros; Raízes de Equações Algébricas Não-Lineares; Sistemas de Equações Algébricas Lineares; Aproximação Numérica."
    ],
    "equivalencias": [
        "CK0175"
    ],
    "justificativa": "",
    "nome": "Métodos Numéricos I",
    "objetivos": [],
    "pre-requisitos": [
        "CK0087"
    ],
    "regime": "semestral",
    "turno": {
        "matutino": true,
        "noturno": false,
        "vespertino": true
    },
    "unidade": "Centro de Ciências"
}

=== DEMA-UFC/mat-ind/_data/componentes-curriculares/pb0148.json
{
    "bibliografia": {
        "basica": [
            "GIL, Antônio Carlos. Métodos e Técnicas de Pesquisa Social. São Paulo, Atlas, 1987.",
            "HUHNE, Leda Maria (org). Metodologia Científica: caderno de textos e técnicas. Rio de Janeiro, Agir, 1987.",
            "RICHARDSON, Roberto Jarry e colaboradores. Pesquisa Social: métodos e técnicas. São Paulo, Atlas, 1985.",
            "RUDIO, Franz Victor. Introdução ao Projeto de Pesquisa Científica. 8ª Ed., Petrópolis, Vozes, 1983."
        ],
        "complementar": [
            "ASTI, Vera Armando. Metodologia da Pesquisa Científica. 7ª Ed. Porto Alegre, Globo, 1983.",
            "LAKATOS, Eva Maria; MARCONI, Marina de Andrade. Fundamentos da Metodologia Científica. São Paulo, Atlas, 1986.",
            "MARCONI, Marina de Andrade; LAKATOS, Eva Maria. Técnicas de Pesquisa: planejamento e execução de pesquisa, amostragens e técnicas de pesquisa, aboração, análise e interpretação de dados. São Paulo, Atlas, 1982."
        ]
    },
    "carga-horaria": {
        "ead": 0,
        "extensao": 0,
        "pratica": 0,
        "semanas": 16,
        "teorica": 64
    },
    "codigo": "PB0148",
    "curso": {
        "carater": "Obrigatório",
        "codigo": "080",
        "curriculo": "2011.1G",
        "grau": "Bacharelado",
        "nome": "Matemática Industrial",
        "semestre": 5
    },
    "departamento": "Fundamentos da Educação",
    "ementa": [
        "A produção científica na universidade. O uso da biblioteca na exploração de documentação bibliográfica. Diretrizes para a interpretação de textos. Noções sobre método e conhecimento. Exercício teórico-prático de acesso a fontes de informação e de elaboração de relatórios: a pesquisa bibliográfica e de campo."
    ],
    "justificativa": "",
    "nome": "Metodologia Científica",
    "objetivos": [
        "Introduzir os conceitos básicos de conhecimento e metodologia científica e fornecer ao aluno as ferramentas científicas necessárias para o desenvolvimento de seus estudos nas universidades."
    ],
    "regime": "semestral",
    "turno": {
        "matutino": true,
        "noturno": false,
        "vespertino": true
    },
    "unidade": "Faculdade de Educação"
}

=== DEMA-UFC/mat-ind/_data/componentes-curriculares/cc0326.json
{
    "bibliografia": {
        "basica": [
            "D. G. de Figueiredo, A. F. Neves. Equações diferenciais aplicadas. IMPA, 2002.",
            "Quarteroni, F. Saleri, P. Gervasio. Scientific computing with MATLAB and Octave. Springer, 2010.",
            "Quarteroni, R. Sacco, F. Saleri. Numerical mathematics. Springer, 2007.",
            "Tveito, R. Winther. Introduction to partial differential equations: a computational approach. Springer, 1998.",
            "R. L. Burden, J. D. Faires. Análise numérica. Pioneira Thomson Learning, 2008.",
            "D. G. Zill, M. R. Cullen. Equações diferenciais, Volume 1. Makron Books, 2001.",
            "D. G. Zill, M. R. Cullen. Equações diferenciais, Volume 2. Makron Books, 2000.",
            "W. E. Boyce. Elementary differential equations and boundary value problems. John Wiley, 2006.",
            "R. Bronson. Differential equations. McGraw-Hill, 2003."
        ],
        "complementar": []
    },
    "carga-horaria": {
        "ead": 0,
        "extensao": 0,
        "pratica": 16,
        "semanas": 16,
        "teorica": 48
    },
    "codigo": "CC0326",
    "curso": {
        "carater": "Eletivo",
        "codigo": "080",
        "curriculo": "2011.1G",
        "grau": "Bacharelado",
        "habilitacao": [
            "Matemática Computacional"
        ],
        "nome": "Matemática Industrial",
        "semestre": 6
    },
    "departamento": "Estatística e Matemática Aplicada",
    "ementa": [
        "O problema de Cauchy, métodos de passo único, equações de diferença, métodos de múltiplos passos, métodos preditores-corretores, métodos Runge-Kutta, sistemas de EDO's, problemas de valor de fronteira, aproximação por diferenças e elementos finitos para o problema de Poisson, aproximação por diferenças e elementos finitos para a equação do calor, equações hiperbólicas, diferenças finitas para a equação do transporte, elementos finitos para a equação de advecção, método de diferenças finitas para a equação de onda e método de elementos finitos para equações hiperbólicas."
    ],
    "justificativa": "As equações diferenciais fazem parte dos modelos de inúmeros ramos da ciência e tecnologia, em especial, daqueles que se baseiam em princípios físicos. Contudo, somente um número muito restrito de equações diferenciais possui solução analítica expressa em uma forma fechada, sendo, portanto necessários o estudo e o desenvolvimento de métodos numéricos para as equações diferenciais. Nesta disciplina, alguns métodos para EDO's abordados em Métodos Numéricos são revisitados, mas o escopo se estende para os métodos numéricos em equações diferenciais parciais e análise de convergência.",
    "nome": "Métodos Numéricos para Equações Diferenciais",
    "objetivos": [
        "Conduzir o aluno no desenvolvimento de conhecimento e experiência em métodos numéricos para equações diferenciais."
    ],
    "pre-requisitos": [
        "CK0048",
        "CB0591"
    ],
    "regime": "semestral",
    "turno": {
        "matutino": true,
        "noturno": false,
        "vespertino": true
    },
    "unidade": "Centro de Ciências"
}
