=== DEMA-UFC/mat-ind/schema/schema-componente-curricular.json
{
	"$schema": "http://json-schema.org/draft-07/schema",
	"title": "Schema para validar um componente curriculare cadastrado nos sistema",
	"definitions": {
		"curso": {
			"tile": "Curso no formulário de criação de disciplina",
			"type": "object",
			"properties": {
				"codigo": {
					"type": "string"
				},
				"nome": {
					"type": "string"
				},
				"grau": {
					"type": "string",
					"enum": [
						"Bacharelado",
						"Licenciatura",
						"Tecnólogo"
					]
				},
				"curriculo": {
					"type": "string"
				},
				"carater": {
					"type": "string",
					"enum": [
						"Obrigatório",
						"Optativo",
						"Eletivo"
					]
				},
				"semestre": {
					"type": "number",
					"minimum": 1,
					"maximum": 8
				},
				"habilitacao": {
					"type": "array",
					"uniqueItems": true,
					"items": {
						"type": "string",
						"enum": [
							"Pesquisa Operacional",
							"Matemática Computacional"
						]
					}
				},
				"unidade-curricular": {
					"title": "Unidade Curricular conforme Projeto Pedagógico do Curso",
					"type": "string",
					"enum": [
						"Métodos Matemáticos",
						"Métodos Estatísticos",
						"Computação",
						"Pesquisa Operacional",
						"Formação Complementar"
					]
				},
				"nucleo-formacao": {
					"title": "Núcleo de Formação conforme Projeto Pedagógico do Curso",
					"type": "string",
					"enum": [
						"Matemática Básica",
						"Computação",
						"Estatística",
						"Matemática Aplicada",
						"Formação Auxiliar",
						"Ênfases",
						"Seminários",
						"Optativa/Livre",
						"Estágio/Monografia",
						"Atividades Complementares"
					]
				}
			},
			"required": [
				"codigo",
				"nome",
				"grau",
				"curriculo",
				"carater"
			]
		},
		"bibliografia": {
			"title": "item de bibliografia de uma disciplina",
			"type": "string"
		}
	},
	"type": "object",
	"properties": {
		"unidade": {
			"type": "string"
		},
		"departamento": {
			"type": "string"
		},
		"curso": {
			"$ref": "#/definitions/curso"
		},
		"nome": {
			"type": "string"
		},
		"codigo": {
			"type": "string"
		},
		"pre-requisitos": {
			"type": "array",
			"uniqueItems": true,
			"items": {
				"type": "string"
			}
		},
		"co-requisitos": {
			"type": "array",
			"uniqueItems": true,
			"items": {
				"type": "string"
			}
		},
		"equivalencias": {
			"type": "array",
			"uniqueItems": true,
			"items": {
				"type": "string"
			}
		},
		"turno": {
			"type": "object",
			"properties": {
				"matutino": {
					"type": "boolean"
				},
				"vespertino": {
					"type": "boolean"
				},
				"noturno": {
					"type": "boolean"
				}
			},
			"required": [
				"matutino",
				"vespertino",
				"noturno"
			]
		},
		"regime": {
			"type": "string",
			"enum": [
				"semestral",
				"anual",
				"modular"
			]
		},
		"justificativa": {
			"type": "string",
			"maxLength": 500
		},
		"objetivos": {
			"type": "array",
			"items": {
				"type": "string"
			}
		},
		"ementa": {
			"$comment": "conforme \"Programa de Disciplina\" aprovado e arquivado pela Unidade Responsável por oferta",
			"type": "array",
			"items": {
				"type": "string"
			}
		},
		"carga-horaria": {
			"type": "object",
			"properties": {
				"semanas": {
					"type": "number",
					"minimum": 0
				},
				"teorica": {
					"type": "number",
					"minimum": 0
				},
				"pratica": {
					"type": "number",
					"minimum": 0
				},
				"ead": {
					"type": "number",
					"minimum": 0
				},
				"extensao": {
					"type": "number",
					"minimum": 0
				}
			}
		},
		"bibliografia": {
			"type": "object",
			"properties": {
				"basica": {
					"type": "array",
					"items": {
						"$ref": "#/definitions/bibliografia"
					},
					"minItems": 3
				},
				"complementar": {
					"type": "array",
					"items": {
						"$ref": "#/definitions/bibliografia"
					},
					"minItems": 5
				}
			}
		},

		"tipo": {
			"title": "Campo somente para atividades.",
			"type": "string",
			"enum": [
				"Estágio Supervisionado",
				"Tutoria/Orientação",
				"Trabalho de Conclusão de Curso/Monografia",
				"Atividades Integradoras de Formação"
			]
		},
		"carga-horaria-docente": {
			"title": "Campo somente para atividades.",
			"type": "number",
			"minimum": 0
		}
	},
	"required": [
		"unidade",
		"curso",
		"nome",
		"codigo",
		"turno",
		"regime",
		"justificativa",
		"objetivos",
		"ementa",
		"carga-horaria",
		"bibliografia"
	]
}

=== DEMA-UFC/mat-ind/_data/componentes-curriculares/cb0535.json
{
    "bibliografia": {
        "basica": [
            "STEWART, J. Cálculo. Vol. 1. Cengage Learning, 6a edição, São Paulo, 2010.",
            "STEWART, J. Cálculo. Vol. 2. Cengage Learning, 6a edição, São Paulo, 2010.",
            "LEITHOLD, L. O Cálculo com Geometria Analítica. Vol. 2, Ed. Harbra, 3a edição, 2002."
        ],
        "complementar": [
            "PINTO, D., MORGADO, M. C. F. Cálculo Diferencial e Integral de Funções de Várias Variáveis. Ed. UFRJ, 3a edição, Rio de Janeiro, 2004.",
            "SANTOS, Â. R. dos; BIANCHINI, W. Aprendendo Cálculo com Maple: cálculo de uma variável. Ed. LTC, 1a edição, Rio de Janeiro, 2002.",
            "SIMMONS, G. F. Cálculo com Geometria Analítica. Vol.2, Ed. Makron Books Pearson Education, 1a edição, São Paulo, 2003.",
            "SWOKOWSKI, E. W. Cálculo com Geometria Analítica. Vol. I, Ed. Makron Books, São Paulo, 1995.",
            "THOMAS, G. B., FINNEY, M. D., WEIR, F. R., GIORDANO, F. R. Cálculo. Vol. I, Ed. Addison Wesley, 2003.",
            "KHURI, A. I. Advanced Calculus with Applications in Statistics. Ed. John Wiley and Sons, 2nd edition, New Jersey, 2003.",
            "TROMBA, A. J., MARSDEN, J. E. Vector Calculus. Ed. W. H. Freeman & Company, 5th edition, New York, 2003."
        ]
    },
    "carga-horaria": {
        "ead": 0,
        "extensao": 0,
        "pratica": 16,
        "semanas": 16,
        "teorica": 80
    },
    "codigo": "CB0535",
    "curso": {
        "carater": "Obrigatório",
        "codigo": "080",
        "curriculo": "2011.1G",
        "grau": "Bacharelado",
        "nome": "Matemática Industrial",
        "semestre": 2
    },
    "departamento": "Matemática",
    "ementa": [
        "Técnicas de integração; Integral imprópria; Polinômio de Taylor; Séries Infinitas; Séries de potências; Métodos numéricos para integral definida e cálculo de raízes de funções; coordenadas polares."
    ],
    "justificativa": "Induzir o conceito de séries. Aplicar o cálculo diferencial para funções de mais de uma variável.",
    "nome": "Cálculo Diferencial e Integral II",
    "objetivos": [
        "Conhecer as definições, conhecer os exemplos e trabalhar com os métodos de integrações."
    ],
    "pre-requisitos": [
        "CB0534"
    ],
    "regime": "semestral",
    "turno": {
        "matutino": true,
        "noturno": false,
        "vespertino": true
    },
    "unidade": "Centro de Ciências"
}

=== DEMA-UFC/mat-ind/_data/componentes-curriculares/cc0399.json
{
    "bibliografia": {
        "basica": [
            "Wolsey. Integer Programming. Wiley, 1998.",
            "G.L. Nemhauser e L.A. Wolsey. Integer and Combinatorial Optimization. John Wiley, 1999.",
            "Schrijver. Theory of Linear and Integer Programming. Wiley, 1998.",
            "C.H. Papadimitriou e K. Steiglitz. Combinatorial Optimization: algorithms and complexity, 1998.",
            "C. Ferreira e Y. Wakabayashi. Combinatória Poliédrica e Planos-de-Corte Faciais. X Escola de Computação, 1996.",
            "H.A. Taha. Integer Programming: theory, applications and computations. Academic Press, 1975.",
            "H.M. Salkin e K. Mathur. Foundation of Integer Programming. North-Holland, 1989.",
            "L. Lasdon. Optimization Theory for Large Systems. MacMillan Pub., 1970.",
            "M.M. Syslo, N. Deo e J.S. Kowalick. Discrete Optimization with Pascal Programs. Prentice-Hall, 1983.",
            "N. Maculan. Programmation Linéaire en Nombres Entiers. Manuscrito, 1983."
        ],
        "complementar": []
    },
    "carga-horaria": {
        "ead": 0,
        "extensao": 0,
        "pratica": 16,
        "semanas": 16,
        "teorica": 48
    },
    "codigo": "CC0399",
    "curso": {
        "carater": "Eletivo",
        "codigo": "080",
        "curriculo": "2011.1G",
        "grau": "Bacharelado",
        "habilitacao": [
            "Pesquisa Operacional"
        ],
        "nome": "Matemática Industrial",
        "semestre": 4
    },
    "departamento": "Estatística e Matemática Aplicada",
    "ementa": [
        "Problemas de programação inteira (PPI). Enumeração Implícita. Método de Balas para PPI 0/1. Otimalidade, Rexalação e Limites. Problemas da Classes P. Métodos branch-andbound. Métodos de planos de corte. Dualidade Lagrangeana. Método de geração de colunas; Métodos de Decomposição: Dantzig-Wolfe e Benders. Aplicações."
    ],
    "justificativa": "Programação inteira é uma disciplina-chave na área de otimização discreta e, consequentemente, indispensável para a formação do profissional da área. Nela, são vistos os principais métodos de solução de problemas de programação inteira.",
    "nome": "Programação Inteira",
    "objetivos": [
        "Capacitar o aluno para modelar e resolver problemas de programação inteira, sabendo identificar as características que podem/devem ser exploradas e podendo encontrar alternativas eficientes de solução."
    ],
    "pre-requisitos": [
        "CC0263"
    ],
    "regime": "semestral",
    "turno": {
        "matutino": true,
        "noturno": false,
        "vespertino": true
    },
    "unidade": "Centro de Ciências"
}

=== DEMA-UFC/mat-ind/_data/componentes-curriculares/cb0536.json
{
    "bibliografia": {
        "basica": [
            "STEWART, J. Cálculo. Cengage Learning, 6a edição, São Paulo, 2010. Vol. 2.",
            "ANTON, H. Cálculo: um novo horizonte. Vol. 2, Ed. Bookman, 6a edição, Porto Alegre, 2000.",
            "KAPLAN, W. Cálculo Avançado. Ed. Edgard Blücher, São Paulo, 2002. Vol. 1."
        ],
        "complementar": [
            "PINTO, D. MORGADO, M. C. F., Cálculo Diferencial e Integral de Funções de Várias Variáveis. Ed. UFRJ, 3a edição, Rio de Janeiro, 2004.",
            "SWOKOWSKI, E. W. Cálculo com Geometria Analítica. Vol. II, Ed. Makron Books, São Paulo, 1995.",
            "THOMAS, G. B., FINNEY, M. D., WEIR, F. R., GIORDANO, F. R. Cálculo. Vol. II e III, Ed. Addison Wesley, 2003.",
            "TROMBA, A. J., MARSDEN, J. E. Vector Calculus. Ed. W. H. Freeman & Company, 5th edition, New York, 2003.",
            "WILLIAMSON, R. E., CROWELL, R. H., TROTTER, H. F. Cálculo de Funções Vetoriais. Ed. Livros Técnicos e Científicos,"
        ]
    },
    "carga-horaria": {
        "ead": 0,
        "extensao": 0,
        "pratica": 16,
        "semanas": 16,
        "teorica": 80
    },
    "codigo": "CB0536",
    "curso": {
        "carater": "Obrigatório",
        "codigo": "080",
        "curriculo": "2011.1G",
        "grau": "Bacharelado",
        "nome": "Matemática Industrial",
        "semestre": 3
    },
    "departamento": "Matemática",
    "ementa": [
        "Curvas e vetores no espaço; Superfícies, plano e quádricas; Funções de várias variáveis; Limite, continuidade e cálculo diferencial de funções reais de várias variáveis reais; Máximos e mínimos e pontos de cela; Multiplicadores de Lagrange; Máximos e mínimos condicionados; Teoremas da função implícita e inversa; Integrais duplas e triplas; mudança de variáveis; Integrais múltiplas impróprias; Integral de linha escalar e vetorial; Teorema de Green; Parametrização e área de superfícies; Integral de superfície escalar e vetorial; Teorema de Stokes e Gauss; Interpretação física; Campos conservativos."
    ],
    "justificativa": "Introduzir o cálculo integral para funções de várias variáveis. Apresentar a teoria do campo.",
    "nome": "Cálculo Diferencial e Integral III",
    "objetivos": [
        "Desenvolver métodos analíticos para aplicações do cálculo de limites, derivadas e integrais de funções de 2 e 3 variáveis. Desenvolver a teoria de máximo e mínimo relativo e absoluto. Desenvolver o estudo de campos vetoriais."
    ],
    "pre-requisitos": [
        "CB0535"
    ],
    "regime": "semestral",
    "turno": {
        "matutino": true,
        "noturno": false,
        "vespertino": true
    },
    "unidade": "Centro de Ciências"
}

=== DEMA-UFC/mat-ind/_data/componentes-curriculares/cc0321.json
{
    "bibliografia": {
        "basica": [
            "F. Glover e Kochenberger G.A. Handbook of metaheuristics. Kluwer, 2003.",
            "El-G. Talbi. Metaheuristics: From design to Implementation. Wiley, 2009.",
            "B. Golden, S. Raghavan e E. Wasil. The vehicle routing problem: Latest advances and new challenges. Springer, 2010. ",
            "M. Arenales, V. Armentano, R. Morabito e H. Yanasse. Pesquisa Operacional. Elsevier, 2007.",
            "M.C. Goldbarg e H.P. Luna. Otimização combinatória e programação linear. Campus/Elsevier, 2005. ",
            "C.R. Reeves. Modern Heuristic Techniques for Combinatorial Problems. Blackwell Scientif Publications, 1993.",
            "F. Glover e M. Laguna. Tabu Search. Kluwer, 1997.",
            "Artigos diversos sobre aplicações de metaheurísticas. Periódicos CAPES."
        ],
        "complementar": []
    },
    "carga-horaria": {
        "ead": 0,
        "extensao": 0,
        "pratica": 48,
        "semanas": 16,
        "teorica": 48
    },
    "codigo": "CC0321",
    "curso": {
        "carater": "Eletivo",
        "codigo": "080",
        "curriculo": "2011.1G",
        "grau": "Bacharelado",
        "habilitacao": [
            "Pesquisa Operacional"
        ],
        "nome": "Matemática Industrial",
        "semestre": 5
    },
    "departamento": "Estatística e Matemática Aplicada",
    "ementa": [
        "Técnicas para solução de problemas de otimização combinatória: Heurísticas clássicas, Metaheurísticas. Principais metaheurísticas: Recozimento Simulado (Simulated Annealing), Busca Tabu, Busca Local Iterada (Iterated Local Search - ILS), Busca em Vizinhança Variável (Variable Neighborhood Search - VNS), Procedimentos de Busca Adaptativa Aleatória e Gulosa (Greedy Randomized Adaptive Search Procedures - GRASP), Algoritmos Genéticos, Colônia de Formigas, Busca Dispersa (Scatter Search). Aplicações"
    ],
    "justificativa": "A disciplina de Otimização Combinatória e Metaheurística apresenta ao aluno diversas formas de resolução de um problema combinatorial. A disciplina contempla aulas expositivas sobre o conteúdo programático e aulas práticas mostrando computacionalmente o desempenho das heurísticas e metaheurísticas estudadas.",
    "nome": "Otimização Combinatória e Metaheurística",
    "objetivos": [
        "Apresentar ao aluno a natureza dos problemas combinatórios e sua dificuldade de resolução. Em seguida, implementar e testar as heurísticas clássicas e as principais metaheurísticas nos diversos problemas combinatoriais."
    ],
    "pre-requisitos": [
        "CC0263"
    ],
    "regime": "semestral",
    "turno": {
        "matutino": true,
        "noturno": false,
        "vespertino": true
    },
    "unidade": "Centro de Ciências"
}

=== DEMA-UFC/mat-ind/_data/componentes-curriculares/cc0315.json
{
    "bibliografia": {
        "basica": [
            "Tachizawa, Takeshy - Como fazer monografia na prática, 12. ed. Publicação Rio de Janeiro, RJ :   FGV,   2006.",
            "Salomon, Délcio Vieira - Como fazer uma monografia, 12. ed., São Paulo, SP :   WMF Martins Fontes,   2010.",
            "Guia de Normalização de Trabalhos Acadêmicos da Universidade Federal do Ceará, 2012., http://www.biblioteca.ufc.br/ acessado em 05/2012."
        ],
        "complementar": []
    },
    "carga-horaria": {
        "ead": 0,
        "extensao": 0,
        "pratica": 128,
        "semanas": 16,
        "teorica": 32
    },
    "codigo": "CC0315",
    "curso": {
        "carater": "Obrigatório",
        "codigo": "080",
        "curriculo": "2011.1G",
        "grau": "Bacharelado",
        "nome": "Matemática Industrial",
        "semestre": 7
    },
    "departamento": "Estatística e Matemática Aplicada",
    "ementa": [
        "Estímulo à produção científica, aprimoramento da capacidade de interpretação e elaboração de um trabalho de conclusão de curso em área específica."
    ],
    "justificativa": "Apresentar aos alunos do curso uma estrutura de projeto de pesquisa além da definição do tema a ser desenvolvido. Ao final o aluno apresentará um relatório final e uma apresentação oral que serão avaliados por uma banca examinadora.",
    "nome": "Monografia I",
    "objetivos": [
        "Propiciar aos alunos do curso o estímulo à produção científica, à consulta bibliográfica especializada e ao aprimoramento da capacidade de interpretação e crítica."
    ],
    "pre-requisitos": [
        "CC0324"
    ],
    "regime": "semestral",
    "turno": {
        "matutino": true,
        "noturno": false,
        "vespertino": true
    },
    "unidade": "Centro de Ciências"
}

=== DEMA-UFC/mat-ind/_data/componentes-curriculares/cb0697.json
{
    "bibliografia": {
        "basica": [
            "LIMA, E. L.; CARVALHO, P. C. P.; WAGNER, E.; MORGADO, A. C. A matemática do ensino médio. Vol 1, SBM, 2012.",
            "MURAKAMI, C. Fundamentos de matemática elementar: conjuntos, funções. Vol. 1, Editora Atual, 2005.",
            "IEZZI, G. Fundamentos de matemática elementar: logaritmos. Vol. 2, Editora Atual, 2005.",
            "IEZZI, G. Fundamentos de matemática elementar: trigonometria. Vol. 3, Editora Atual, 2005.",
            "IEZZI, G. Fundamentos de matemática elementar: geometria analítica. Vol. 7, Editora Atual, 2005.",
            "LARSON, R. Precalculus functions and graphs, a graphing approach. Houghton Mifflin Company, 2005."
        ],
        "complementar": []
    },
    "carga-horaria": {
        "ead": 0,
        "extensao": 0,
        "pratica": 0,
        "semanas": 16,
        "teorica": 64
    },
    "codigo": "CB0697",
    "curso": {
        "carater": "Obrigatório",
        "codigo": "080",
        "curriculo": "2011.1G",
        "grau": "Bacharelado",
        "nome": "Matemática Industrial",
        "semestre": 1
    },
    "departamento": "Matemática",
    "ementa": [
        "Conjuntos numéricos, conceitos de funções, tipos de funções, operações com funções, funções polinominais, funções racionais, funções exponenciais, funções logarítmicas, funções trigonométricas, representação gráfica de funções, geometria analítica no espaço, reta e plano cartesianos."
    ],
    "justificativa": "",
    "nome": "Elementos de Matemática",
    "objetivos": [
        "Introduzir/revisar conceitos básicos sobre conjuntos, funções, representações gráficas e geometria analítica."
    ],
    "regime": "semestral",
    "turno": {
        "matutino": true,
        "noturno": false,
        "vespertino": true
    },
    "unidade": "Centro de Ciências"
}

=== DEMA-UFC/mat-ind/_data/componentes-curriculares/cc0280.json
{
    "bibliografia": {
        "basica": [
            "MOORE, D.S. A estatística básica e sua prática. 3. ed. Rio de Janeiro: LTC, 2005.",
            "FERREIRA, D.F. Estatística básica. Lavras, MG: Editora UFLA, 2005.",
            "BUSSAB, W.O.; MORETTIN, P.A. Estatística básica. 5.ed. São Paulo: Saraiva, 2005.",
            "TOLEDO, G.L.; OVALLE, I.I. Estatística básica. 2. ed. Sao Paulo: Atlas, 1985."
        ],
        "complementar": []
    },
    "carga-horaria": {
        "ead": 0,
        "extensao": 0,
        "pratica": 16,
        "semanas": 16,
        "teorica": 48
    },
    "codigo": "CC0280",
    "curso": {
        "carater": "Obrigatório",
        "codigo": "080",
        "curriculo": "2011.1G",
        "grau": "Bacharelado",
        "nome": "Matemática Industrial",
        "semestre": 2
    },
    "departamento": "Estatística e Matemática Aplicada",
    "ementa": [
        "Introdução à Estatística; tipos de variáveis; análise exploratória de variáveis qualitativas; análise exploratória de variáveis quantitativas; análise bidimensional; utilização de ferramenta computacional."
    ],
    "justificativa": "No mundo moderno as facilidades oferecidas pela divulgação de informações, assim como o desenvolvimento de novas ferramentas estatísticas de maior complexidade tornam o conhecimento básico da ciência estatística uma necessidade. Para o aluno recém-ingresso no Curso de Estatística, deparar-se com aplicações da estatística, mesmo sem grandes aprofundamentos teóricos, é de grande valia para uma iniciação profissional.",
    "nome": "Análise Exploratória de Dados",
    "objetivos": [
        "No final da disciplina o aluno deve: conhecer conceitos básicos da Estatística; identificar tipos de variáveis e calcular e interpretar as medidas resumo apropriadas para cada tipo de variável; identificar e construir representações gráficas apropriadas para descrever fenômenos; construir tabelas; interpretar tabelas e gráficos; identificar e calcular medidas de associação apropriadas para  variáveis qualitativas e ou quantitativas; manipular um programa computacional para o cálculo de estatísticas e construção de tabelas e gráficos."
    ],
    "regime": "semestral",
    "turno": {
        "matutino": true,
        "noturno": false,
        "vespertino": true
    },
    "unidade": "Centro de Ciências"
}

=== DEMA-UFC/mat-ind/_data/componentes-curriculares/cc0317.json
{
    "bibliografia": {
        "basica": [
            "Stela C. Bertholo Piconez (coord.); Ivani Catarina Arantes Fazenda - A Prática de ensino e o estágio supervisionado, 23. ed. Publicação Campinas, SP :   Papirus,   2010.",
            "Bianchi, Anna Cecília de Moraes - Manual de orientação: Estágio supervisionado, 4. ed. São Paulo, SP :   Cengage Learning,   2011.",
            "Guia de Normalização de Trabalhos Acadêmicos da Universidade Federal do Ceará, 2012., http://www.biblioteca.ufc.br/ acessado em 05/2012."
        ],
        "complementar": []
    },
    "carga-horaria": {
        "ead": 0,
        "extensao": 0,
        "pratica": 128,
        "semanas": 16,
        "teorica": 32
    },
    "codigo": "CC0317",
    "curso": {
        "carater": "Obrigatório",
        "codigo": "080",
        "curriculo": "2011.1G",
        "grau": "Bacharelado",
        "nome": "Matemática Industrial",
        "semestre": 7
    },
    "departamento": "Estatística e Matemática Aplicada",
    "ementa": [
        "Atividades ligadas à prática profissional, que capacitem o estudante a atuar no mercado de trabalho integrado de forma cooperativa, concretizando objetivos previamente estabelecidos. Essas atividades podem ser realizadas na Universidade ou em outras instituições de Pesquisa, empresas públicas ou privadas e órgãos conveniados."
    ],
    "justificativa": "Partindo da premissa de que o fazer pedagógico requer momentos de planejamento, execução e avaliação do trabalho, proporcionando um intercâmbio entre a realidade e a educação, através de uma prática que envolva o saber pedagógico, o saber científico, o saber político e o social, o Estágio Supervisionado I justifica-se por sua finalidade de orientar e acompanhar as atividades dos alunos do curso de Matemática Industrial na Universidade ou em outras instituições de Pesquisa, empresas públicas ou privadas e órgãos conveniados. Ao final o aluno apresentará um relatório final e uma apresentação oral que serão avaliados por uma banca examinadora.",
    "nome": "Estágio Supervisionado I",
    "objetivos": [
        "Propiciar aos alunos ambientes adequados para que possam ser capazes de aplicar metodologias, técnicas e ferramentas estudadas ao longo do curso, desenvolvendo habilidades práticas, como formação complementar. Proporcionar a Vicência de situações reais nas quais possam com base no conhecimento teórico desenvolvido nas disciplinas do curso, buscar a unidade teoria e prática."
    ],
    "pre-requisitos": [
        "CC0324"
    ],
    "regime": "semestral",
    "turno": {
        "matutino": true,
        "noturno": false,
        "vespertino": true
    },
    "unidade": "Centro de Ciências"
}
